---
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0
  extra_joints:
    - name: $(arg prefix)left_rocker_joint
      position: 0.0
    - name: $(arg prefix)left_caster_support_joint
      position: 0.0
    - name: $(arg prefix)left_caster_joint
      position: 0.0
    - name: $(arg prefix)rear_left_caster_support_joint
      position: 0.0
    - name: $(arg prefix)rear_left_caster_joint
      position: 0.0
    - name: $(arg prefix)right_rocker_joint
      position: 0.0
    - name: $(arg prefix)right_caster_support_joint
      position: 0.0
    - name: $(arg prefix)right_caster_joint
      position: 0.0
    - name: $(arg prefix)rear_right_caster_support_joint
      position: 0.0
    - name: $(arg prefix)rear_right_caster_joint
      position: 0.0


robotnik_base_control:
  type: diff_drive_controller/DiffDriveController
  left_wheel: $(arg prefix)left_wheel_joint
  right_wheel: $(arg prefix)right_wheel_joint
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation: 0.4553
  wheel_radius: 0.07

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier: 1.0

  cmd_vel_timeout: 0.25

  # Base frame_id
  odom_frame_id: $(arg prefix)odom
  base_frame_id: $(arg prefix)base_footprint

  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.5
      has_jerk_limits: false
      max_jerk: 0.0
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 3.1416
      has_acceleration_limits: true
      max_acceleration: 6.2832
      has_jerk_limits: false
      max_jerk: 0.0


robotnik_arm_control:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg prefix)arm_column_joint
    - $(arg prefix)arm_inner_joint
    - $(arg prefix)arm_outer_joint
    - $(arg prefix)arm_wrist_joint
  constraints:
    stopped_velocity_tolerance: 0
    $(arg prefix)arm_column_joint:
      goal: 0.1
    $(arg prefix)arm_inner_joint:
      goal: 0.1
    $(arg prefix)arm_outer_joint:
      goal: 0.1
    $(arg prefix)arm_wrist_joint:
      goal: 0.1
  gains:
    $(arg prefix)arm_column_joint: {p: 16000.0, i: 30000.0, d: 40.0, i_clamp: 30000.0}
    $(arg prefix)arm_inner_joint:  {p: 16000.0, i: 1000.0,  d: 2.0,  i_clamp: 30000.0}
    $(arg prefix)arm_outer_joint:  {p: 10000.0, i: 1000.0,  d: 2.0,  i_clamp: 30000.0}
    $(arg prefix)arm_wrist_joint:  {p: 10000.0, i: 1000.0,  d: 2.0,  i_clamp: 30000.0}
