controller_list:
  - name: fake_ur10e_arm_controller
    type: $(arg execution_type)
    joints:
      - robot_arm_shoulder_pan_joint
      - robot_arm_shoulder_lift_joint
      - robot_arm_elbow_joint
      - robot_arm_wrist_1_joint
      - robot_arm_wrist_2_joint
      - robot_arm_wrist_3_joint
initial:  # Define initial robot poses.
  - group: ur10e_arm
    pose: home